/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AzplBgk1886
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ResponsiveBar } from '@nivo/bar'
import { ResponsiveLine } from '@nivo/line'

export function Charts() {
  return (
    <div className='flex flex-col gap-8'>
      <div className='grid grid-cols-2 gap-6'>
        <Card className='col-span-1'>
          <CardHeader className='flex justify-between'>
            <CardTitle>Employees</CardTitle>
            <Button className='text-xs' variant='ghost'>
              ...
            </Button>
          </CardHeader>
          <CardContent className='flex items-center justify-between'>
            <div className='text-2xl font-bold'>60 people</div>
            <div className='flex items-center text-sm text-green-500'>
              <ArrowUpIcon className='h-4 w-4 mr-1' />
              +0.7%{'\n'}
            </div>
          </CardContent>
        </Card>
        <Card className='col-span-1'>
          <CardHeader className='flex justify-between'>
            <CardTitle>Clients</CardTitle>
            <Button className='text-xs' variant='ghost'>
              ...
            </Button>
          </CardHeader>
          <CardContent className='flex items-center justify-between'>
            <div className='text-2xl font-bold'>240 people</div>
            <div className='flex items-center text-sm text-red-500'>
              <ArrowDownIcon className='h-4 w-4 mr-1' />
              -1.7%{'\n'}
            </div>
          </CardContent>
        </Card>
      </div>
      <div className='grid grid-cols-2 gap-6'>
        <div className='col-span-1'>
          <BarChart className='w-full h-[200px]' />
        </div>
        <Card className='col-span-1'>
          <CardHeader>
            <CardTitle>Distribution</CardTitle>
          </CardHeader>
          <CardContent>
            <div className='flex justify-between'>
              <div>Russia</div>
              <div className='text-right'>
                <div className='font-bold'>62%</div>
                <div className='text-xs text-slate-500 dark:text-slate-400'>
                  Kazan
                </div>
              </div>
            </div>
            <div className='flex justify-between'>
              <div>USA</div>
              <div className='text-right'>
                <div className='font-bold'>20%</div>
                <div className='text-xs text-slate-500 dark:text-slate-400'>
                  California
                </div>
              </div>
            </div>
            <div className='flex justify-between'>
              <div>Germany</div>
              <div className='text-right'>
                <div className='font-bold'>18%</div>
                <div className='text-xs text-slate-500 dark:text-slate-400'>
                  Berlin
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader className='flex justify-between'>
          <CardTitle>Interaction List</CardTitle>
          <div className='flex items-center space-x-2'>
            <Button size='sm' variant='ghost'>
              31/12/2021 - 01/04/2022
            </Button>
            <Button size='sm' variant='ghost'>
              Total
            </Button>
            <Button size='sm' variant='ghost'>
              Follower
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <CurvedlineChart className='w-full h-[200px]' />
        </CardContent>
      </Card>
    </div>
  )
}

function ArrowDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M12 5v14' />
      <path d='m19 12-7 7-7-7' />
    </svg>
  )
}

function ArrowUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='m5 12 7-7 7 7' />
      <path d='M12 19V5' />
    </svg>
  )
}

function BarChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: 'Jan', count: 111 },
          { name: 'Feb', count: 157 },
          { name: 'Mar', count: 129 },
          { name: 'Apr', count: 150 },
          { name: 'May', count: 119 },
          { name: 'Jun', count: 72 }
        ]}
        keys={['count']}
        indexBy='name'
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={['#2563eb']}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: '9999px'
            },
            container: {
              fontSize: '12px',
              textTransform: 'capitalize',
              borderRadius: '6px'
            }
          },
          grid: {
            line: {
              stroke: '#f3f4f6'
            }
          }
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role='application'
        ariaLabel='A bar chart showing data'
      />
    </div>
  )
}

function CurvedlineChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: 'Desktop',
            data: [
              { x: 'Jan', y: 43 },
              { x: 'Feb', y: 137 },
              { x: 'Mar', y: 61 },
              { x: 'Apr', y: 145 },
              { x: 'May', y: 26 },
              { x: 'Jun', y: 154 }
            ]
          },
          {
            id: 'Mobile',
            data: [
              { x: 'Jan', y: 60 },
              { x: 'Feb', y: 48 },
              { x: 'Mar', y: 177 },
              { x: 'Apr', y: 78 },
              { x: 'May', y: 96 },
              { x: 'Jun', y: 204 }
            ]
          }
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: 'point'
        }}
        yScale={{
          type: 'linear',
          min: 0,
          max: 'auto'
        }}
        curve='monotoneX'
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16
        }}
        colors={['#2563eb', '#e11d48']}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: '9999px'
            },
            container: {
              fontSize: '12px',
              textTransform: 'capitalize',
              borderRadius: '6px'
            }
          },
          grid: {
            line: {
              stroke: '#f3f4f6'
            }
          }
        }}
        role='application'
      />
    </div>
  )
}
